site_name: Board Puzzle Algorithms
repo_url: https://github.com/Jtachan/Puzzles-Algorithms

nav:
  - Home: 'index.md'
  - Puzzles:
      - Sudoku: 'sudoku/readme.md'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.footer
    - navigation.sections
    - search.suggest
    - search.highlight
markdown_extensions:
  # some selected markdown extensions
  # feel free to add more
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
plugins:
  - search
